name: Build dae unstable.apk

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

permissions:
  actions: write
  contents: write

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64_generic
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3-setuptools rsync swig unzip zlib1g-dev file wget

      - name: Generate build keys
        run: |
          sudo apt-get update
          sudo apt-get install -y signify-openbsd
          signify-openbsd -G -n -c 'DO NOT USE - OpenWrt packages feed CI' -p packages_ci.pub -s packages_ci.sec
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "KEY_BUILD<<$EOF" >> $GITHUB_ENV
          cat packages_ci.sec >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV

      - name: Setup latest golang release
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Show go version
        run: |
          go version

      - name: Get dae alpha
        run: |
          git clone https://github.com/daeuniverse/dae -b main
          cd dae
          VER="$(git log -1 --format="%cd" --date=format:'%Y%m%d%H%M%S' | sed s/-//g)"~"$(git rev-parse --short HEAD)"
          HEAD_REF=$(git rev-parse HEAD)
          echo "PKG_VER=$VER" >> $GITHUB_ENV
          echo "HEAD_REF=$HEAD_REF" >> $GITHUB_ENV
          cd -

      - name: Build
        run: |
          SDK=$(curl -s -L https://downloads.immortalwrt.org/snapshots/targets/rockchip/armv8/sha256sums | grep sdk | sed 's/.* \*//')
          wget https://downloads.immortalwrt.org/snapshots/targets/rockchip/armv8/$SDK -O sdk.tar.xz

          mkdir sdk
          tar -I zstd -xf sdk.tar.xz --strip-components=1 -C sdk
          cd sdk
          ./scripts/feeds update -a
          wget https://downloads.immortalwrt.org/snapshots/targets/rockchip/armv8/config.buildinfo -O .config
          make defconfig
          cp -a ../net package/
          mv package/net/dae/git.Makefile package/net/dae/Makefile
          sed -i 's/PKG_VERSION:=unstable/PKG_VERSION:=${{ env.PKG_VER }}/g' package/net/dae/Makefile
          sed -i 's/PKG_SOURCE_VERSION:=unstable/PKG_SOURCE_VERSION:=${{ env.HEAD_REF }}/g' package/net/dae/Makefile
          make package/net/dae/{download,check} FIXUP=1 V=s
          make package/net/dae/compile V=s

          FN=$(find bin/packages -name 'dae*.apk' | sort | head -1 | xargs basename)
          echo "PKG_NAME=$FN" >> $GITHUB_ENV
          cd -
          find sdk/bin/packages -maxdepth 10

      - name: Publishing to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PKG_NAME }}
          path: |
            sdk/bin/packages/*/*/dae*.apk

      - name: Read release.md and use it as a body of new release
        id: read_release
        shell: bash
        run: |
          r=$(cat README.md)
          r="${r//'%'/'%25'}"
          r="${r//$'\n'/'%0A'}"
          r="${r//$'\r'/'%0D'}"
          echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT

      - name: Publishing to GitHub Releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sdk/bin/packages/*/*/dae*.apk
          tag: latest
          file_glob: true
          overwrite: true
          body: |
            ${{ steps.read_release.outputs.RELEASE_BODY }}
